{"timestamp":"2025-07-24T06:44:25.166544","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-24T06:44:25.167397","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_to_snowflake.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-24T06:44:27.575597","level":"info","event":"Snowflake Connector for Python Version: 3.16.0, Python Version: 3.12.11, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36","logger":"snowflake.connector.connection"}
{"timestamp":"2025-07-24T06:44:27.576658","level":"info","event":"Connecting to GLOBAL Snowflake domain","logger":"snowflake.connector.connection"}
{"timestamp":"2025-07-24T06:44:30.185183","level":"warning","event":"Certificate did not match expected hostname: pc20898.gcp_me_central2.gcp.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}","logger":"snowflake.connector.vendored.urllib3.connection"}
{"timestamp":"2025-07-24T06:44:30.185906","level":"warning","event":"Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError(\"hostname 'pc20898.gcp_me_central2.gcp.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'\"))': /session/v1/login-request?request_id=0b91e06c-998d-4993-9e4b-eeebc516649a&databaseName=AIRFLOW_PIPELINE&schemaName=PUBLIC&warehouse=COMPUTE_WH&request_guid=184551e8-ec03-4385-8fab-2823b7eb981c","logger":"snowflake.connector.vendored.urllib3.connectionpool"}
{"timestamp":"2025-07-24T06:44:30.963053","level":"warning","event":"Certificate did not match expected hostname: pc20898.gcp_me_central2.gcp.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}","logger":"snowflake.connector.vendored.urllib3.connection"}
{"timestamp":"2025-07-24T06:44:32.806199","level":"warning","event":"Certificate did not match expected hostname: pc20898.gcp_me_central2.gcp.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}","logger":"snowflake.connector.vendored.urllib3.connection"}
{"timestamp":"2025-07-24T06:44:32.807157","level":"warning","event":"Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError(\"hostname 'pc20898.gcp_me_central2.gcp.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'\"))': /session/v1/login-request?request_id=2aeb2d6e-5349-49e5-aa99-f7dbd4949d34&databaseName=AIRFLOW_PIPELINE&schemaName=PUBLIC&warehouse=COMPUTE_WH&request_guid=b04eb757-f071-492e-9fcb-5599892a9a0b","logger":"snowflake.connector.vendored.urllib3.connectionpool"}
{"timestamp":"2025-07-24T06:44:33.627524","level":"warning","event":"Certificate did not match expected hostname: pc20898.gcp_me_central2.gcp.snowflakecomputing.com. Certificate: {'subject': ((('commonName', '*.prod3.us-west-2.snowflakecomputing.com'),),), 'subjectAltName': [('DNS', '*.prod3.us-west-2.snowflakecomputing.com'), ('DNS', '*.us-west-2.snowflakecomputing.com'), ('DNS', '*.global.snowflakecomputing.com'), ('DNS', '*.snowflakecomputing.com'), ('DNS', '*.prod3.us-west-2.aws.snowflakecomputing.com')]}","logger":"snowflake.connector.vendored.urllib3.connection"}
{"timestamp":"2025-07-24T06:44:33.638161","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"250001: 250001: Could not connect to Snowflake backend after 2 attempt(s).Aborting\nVerify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.\nTo further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/app/salary/extract_sqlite.py","lineno":24,"name":"extract_sqlite"},{"filename":"/opt/airflow/utils/snowflake_uploader.py","lineno":8,"name":"upload_to_snowflake"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/__init__.py","lineno":54,"name":"Connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":554,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":911,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":1312,"name":"__open_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":1637,"name":"authenticate_with_retry"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":1715,"name":"_authenticate"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":1690,"name":"_authenticate"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/auth/by_plugin.py","lineno":212,"name":"handle_timeout"}],"is_group":false,"exceptions":[]},{"exc_type":"OperationalError","exc_value":"250003: 250003: Hit non-retryable SSL error, HTTPSConnectionPool(host='pc20898.gcp_me_central2.gcp.snowflakecomputing.com', port=443): Max retries exceeded with url: /session/v1/login-request?request_id=0b91e06c-998d-4993-9e4b-eeebc516649a&databaseName=AIRFLOW_PIPELINE&schemaName=PUBLIC&warehouse=COMPUTE_WH&request_guid=184551e8-ec03-4385-8fab-2823b7eb981c (Caused by SSLError(CertificateError(\"hostname 'pc20898.gcp_me_central2.gcp.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'\"))).\nVerify that the hostnames and port numbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.\nTo further troubleshoot your connection you may reference the following article: https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/connection.py","lineno":1669,"name":"_authenticate"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/auth/_auth.py","lineno":226,"name":"authenticate"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":805,"name":"_post_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":924,"name":"fetch"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":1054,"name":"_request_exec_wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":975,"name":"_request_exec_wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":1219,"name":"_request_exec"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py","lineno":279,"name":"errorhandler_wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py","lineno":337,"name":"hand_to_other_handler"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py","lineno":210,"name":"default_errorhandler"}],"is_group":false,"exceptions":[]},{"exc_type":"SSLError","exc_value":"HTTPSConnectionPool(host='pc20898.gcp_me_central2.gcp.snowflakecomputing.com', port=443): Max retries exceeded with url: /session/v1/login-request?request_id=0b91e06c-998d-4993-9e4b-eeebc516649a&databaseName=AIRFLOW_PIPELINE&schemaName=PUBLIC&warehouse=COMPUTE_WH&request_guid=184551e8-ec03-4385-8fab-2823b7eb981c (Caused by SSLError(CertificateError(\"hostname 'pc20898.gcp_me_central2.gcp.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'\")))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/network.py","lineno":1149,"name":"_request_exec"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py","lineno":589,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/adapters.py","lineno":516,"name":"send"}],"is_group":false,"exceptions":[]},{"exc_type":"MaxRetryError","exc_value":"HTTPSConnectionPool(host='pc20898.gcp_me_central2.gcp.snowflakecomputing.com', port=443): Max retries exceeded with url: /session/v1/login-request?request_id=0b91e06c-998d-4993-9e4b-eeebc516649a&databaseName=AIRFLOW_PIPELINE&schemaName=PUBLIC&warehouse=COMPUTE_WH&request_guid=184551e8-ec03-4385-8fab-2823b7eb981c (Caused by SSLError(CertificateError(\"hostname 'pc20898.gcp_me_central2.gcp.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'\")))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/requests/adapters.py","lineno":485,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py","lineno":827,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py","lineno":799,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/retry.py","lineno":592,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"CertificateError","exc_value":"hostname 'pc20898.gcp_me_central2.gcp.snowflakecomputing.com' doesn't match either of '*.prod3.us-west-2.snowflakecomputing.com', '*.us-west-2.snowflakecomputing.com', '*.global.snowflakecomputing.com', '*.snowflakecomputing.com', '*.prod3.us-west-2.aws.snowflakecomputing.com'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py","lineno":715,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py","lineno":404,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connectionpool.py","lineno":1058,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connection.py","lineno":472,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/connection.py","lineno":545,"name":"_match_hostname"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/vendored/urllib3/util/ssl_match_hostname.py","lineno":150,"name":"match_hostname"}],"is_group":false,"exceptions":[]}]}
